const Contry: { [key: string]: string } = {
  Ghana: '가나',
  Gabon: '가봉',
  Guyana: '가이아나',
  Gambia: '감비아',
  Guam: '괌',
  Guadeloupe: '과들루프',
  Guatemala: '과테말라',
  Grenada: '그레나다',
  Greece: '그리스',
  Greenland: '그린란드',
  Guinea: '기니',
  'Guinea-Bissau': '기니비사우',
  Namibia: '나미비아',
  Nauru: '나우루',
  Nigeria: '나이지리아',
  'South Sudan': '남수단',
  'South Africa': '남아프리카 공화국',
  'the Netherlands': '네덜란드',
  Nepal: '네팔',
  Norway: '노르웨이',
  'New Caledonia': '누벨칼레도니',
  'New Zealand': '뉴질랜드',
  Niue: '니우에',
  Niger: '니제르',
  Nicaragua: '니카라과',
  'Republic of Korea': '대한민국',
  Denmark: '덴마크',
  'Dominican R.': '도미니카 공화국',
  Dominica: '도미니카 연방',
  Germany: '독일',
  'East Timor': '동티모르',
  Laos: '라오스',
  Liberia: '라이베리아',
  Latvia: '라트비아',
  Russia: '러시아',
  Lebanon: '레바논',
  Lesotho: '레소토',
  Romania: '루마니아',
  Luxembourg: '룩셈부르크',
  Rwanda: '르완다',
  Libya: '리비아',
  Lithuania: '리투아니아',
  Liechtenstein: '리히텐슈타인',
  Madagascar: '마다가스카르',
  Martinique: '마르티니크',
  'Marshall Islands': '마셜 제도',
  Mayotte: '마요트',
  Macao: '마카오',
  Malawi: '말라위',
  Malaysia: '말레이시아',
  Mali: '말리',
  Mexico: '멕시코',
  Monaco: '모나코',
  Morocco: '모로코',
  Mauritius: '모리셔스',
  Mauritania: '모리타니',
  Mozambique: '모잠비크',
  Montenegro: '몬테네그로',
  Montserrat: '몬트세랫',
  Maldova: '몰도바',
  Maldives: '몰디브',
  Malta: '몰타',
  Mongolia: '몽골',
  'United States of America': '미국',
  Myanmar: '미얀마 (버마)',
  Micronesia: '미크로네시아 연방',
  Vanuatu: '바누아투',
  Bahrain: '바레인',
  Barbados: '바베이도스',
  Vatican: '바티칸 시국',
  Bahamas: '바하마',
  Bangladesh: '방글라데시',
  Bermuda: '버뮤다',
  Benin: '베냉',
  Venezuela: '베네수엘라',
  Vietnam: '베트남',
  Belgium: '벨기에',
  Belarus: '벨라루스',
  Belize: '벨리즈',
  'Bosnia and Herzegovina': '보스니아 헤르체고비나',
  Botswana: '보츠와나',
  Bolivia: '볼리비아',
  Burundi: '부룬디',
  'Burkina Faso': '부르키나파소',
  Bhutan: '부탄',
  Macedonia: '북마케도니아',
  Bulgaria: '불가리아',
  Brazil: '브라질',
  Brunei: '브루나이',
  Samoa: '사모아',
  'Saudi Arabia': '사우디아라비아',
  'San Marino': '산마리노',
  'Saint Pierre and Miquelon': '생피에르 미클롱',
  'Western Sahara': '서사하라',
  Senegal: '세네갈',
  Serbia: '세르비아',
  Seychelles: '세이셸',
  'Saint Lucia': '세인트루시아',
  'Saint Helena': '세인트헬레나',
  Somalia: '소말리아',
  'Solomon Islands': '솔로몬 제도',
  Sudan: '수단',
  Suriname: '수리남',
  'Sri Lanka': '스리랑카',
  Sweden: '스웨덴',
  Switzerland: '스위스',
  Spain: '스페인',
  Slovakia: '슬로바키아',
  Slovenia: '슬로베니아',
  Syria: '시리아',
  'Sierra Leone': '시에라리온',
  'Sint Maarten': '신트마르턴',
  Singapore: '싱가포르',
  'United Arab Emirates': '아랍에미리트',
  Aruba: '아루바',
  Armenia: '아르메니아',
  Argentina: '아르헨티나',
  'American Samoa': '아메리칸사모아',
  Iceland: '아이슬란드',
  Haiti: '아이티',
  Ireland: '아일랜드',
  Azerbaijan: '아제르바이잔',
  Afghanistan: '아프가니스탄',
  Andorra: '안도라',
  Albania: '알바니아',
  Algeria: '알제리',
  Angola: '앙골라',
  'Antigua and Barbuda': '앤티가 바부다',
  Anguilla: '앵귈라',
  Eritrea: '에리트레아',
  Eswatini: '에스와티니',
  Estonia: '에스토니아',
  Ecuador: '에콰도르',
  Ethiopia: '에티오피아',
  'El Salvador': '엘살바도르',
  'United Kingdom': '영국',
  Yemen: '예멘',
  Oman: '오만',
  Australia: '오스트레일리아',
  Austria: '오스트리아',
  Honduras: '온두라스',
  Jordan: '요르단',
  Uganda: '우간다',
  Uruguay: '우루과이',
  Uzbekistan: '우즈베키스탄',
  Ukraine: '우크라이나',
  Iraq: '이라크',
  Iran: '이란',
  Israel: '이스라엘',
  Egypt: '이집트',
  Italy: '이탈리아',
  India: '인도',
  Indonesia: '인도네시아',
  Japan: '일본',
  Jamaica: '자메이카',
  Zambia: '잠비아',
  'Equatorial Guinea': '적도 기니',
  'DPR of Korea': '북한',
  Georgia: '조지아',
  'Central Africa': '중앙아프리카 공화국',
  Taiwan: '대만',
  China: '중화인민공화국',
  Djibouti: '지부티',
  Gibraltar: '지브롤터',
  Zimbabwe: '짐바브웨',
  Chad: '차드',
  Czech: '체코',
  Chile: '칠레',
  Cameroon: '카메룬',
  'Cape Verde': '카보베르데',
  Kazakstan: '카자흐스탄',
  Qatar: '카타르',
  Cambodia: '캄보디아',
  Canada: '캐나다',
  Kenya: '케냐',
  'Cayman Islands': '케이맨 제도',
  'the Comoros': '코모로',
  'Costa Rica': '코스타리카',
  'Ivory Coast': '코트디부아르',
  Colombia: '콜롬비아',
  Congo: '콩고 공화국',
  'DR Congo': '콩고 민주 공화국',
  Cuba: '쿠바',
  Kuwait: '쿠웨이트',
  'Cook Islands': '쿡 제도',
  Croatia: '크로아티아',
  Kyrgizstan: '키르기스스탄',
  Kiribati: '키리바시',
  Cyprus: '키프로스',
  Tajikistan: '타지키스탄',
  Tanzania: '탄자니아',
  Thailand: '태국',
  Turkey: '터키',
  Togo: '토고',
  Tokelau: '토켈라우',
  Tonga: '통가',
  Turkmenistan: '투르크메니스탄',
  Tuvalu: '투발루',
  Tunisia: '튀니지',
  'Trinidad and Tobago': '트리니다드 토바고',
  Panama: '파나마',
  Paraguay: '파라과이',
  Pakistan: '파키스탄',
  'Papua New Guinea': '파푸아뉴기니',
  Palau: '팔라우',
  'State of Palestine': '팔레스타인',
  Peru: '페루',
  Portugal: '포르투갈',
  'Falkland Islands': '포클랜드 제도',
  Poland: '폴란드',
  'Puerto Rico': '푸에르토리코',
  France: '프랑스',
  Fiji: '피지',
  Finland: '핀란드',
  'the Philippines': '필리핀',
  Hungary: '헝가리',
  'Hong Kong': '홍콩',
};

export { Contry };
